// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FyCWhYHdaaP97xoLSHbG5jvzTdMHstM',
    appId: '1:580683511614:android:0caeac11ba987afdaf9e6f',
    messagingSenderId: '580683511614',
    projectId: 'shoppu-ab788',
    storageBucket: 'shoppu-ab788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaSIrsTRwwvEOx_6CB44J_SfaFfp3O1Q',
    appId: '1:580683511614:ios:dd01a8e45c58d9d9af9e6f',
    messagingSenderId: '580683511614',
    projectId: 'shoppu-ab788',
    storageBucket: 'shoppu-ab788.appspot.com',
    iosClientId:
        '580683511614-6btms088don3b6kiu2br271e6sgtgi51.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppu',
  );
}
